function outStimDir = im_pscrambledir(stimDir, nPerStim, matrixFieldname)
% outStimDir = im_pscrambledir(stimDir, matrixFieldname)
%
% This function generates the phase scrambled for the stimulus direcgtory.
%
% Inputs:
%     stimDir          <structure> stimulus structure [generated by
%                       im_readdir].
%     nPerStim         <integer> how many scrambled images will be created
%                       for each stimulus. Default is 1.
%     matrixFieldname  <fieldname> the fieldname for the image matrix.
%
% Output:
%     outStimDir       <structure> stimulus structure [a new
%     fieldname called .psmatrix is added.
%
% Created by Haiyang Jin (20-Feb-2020)
%
% See also:
% im_bscrambledir

% obtain the cell of stimulus matrix
if ~exist('matrixFieldname', 'var') || isempty(matrixFieldname)
    matrixCell = {stimDir.matrix};
else
    matrixCell = {stimDir.(matrixFieldname)};
end

tmpStimDir = stimDir;
outCell = cell(nPerStim, 1);

for iRound = 1:nPerStim
    
    % generated the phase scrambled matrix
    scrambledCell = cellfun(@im_phasescramble, matrixCell, 'uni', false);
    
    % save the phase-scrambled matrix as a new fiedlname
    [tmpStimDir.psmatrix] = deal(scrambledCell{:});
    
    % save the round number
    roundCell = num2cell(ones(size(tmpStimDir))*iRound);
    [tmpStimDir.round] = deal(roundCell{:});
    
    % save the scrambled for this round
    outCell{iRound, 1} = tmpStimDir;
    
end

outStimDir = vertcat(outCell{:});

end