function stimDir = im_resize(stimDir, scale, matrixFieldname)
% stimDir = im_resize(stimDir, scale, matrixFieldname)
%
% This function use imresize to resize the image matrix.
%
% Inputs:
%    stimDir   <structure> the image dir (generated by im_readdir.m).
%    scale     <numeric> the scale will be applied to the image. If scale <
%               1, the output image will be smaller; if scale > 1, the
%               output image will be larger.
%
% Output:
%    stimDir   <structure> the stimulus structure with newly added
%               fieldnames saving the resized matrix/alpha. 
%
% Created by Haiyang Jin (06-Oct-2020)
%
% See also:
% im_dir, im_readdir, im_writedir

if ~exist('scale', 'var') || isempty(scale)
    scale = 0.5;
end

if ~exist('matrixFieldname', 'var') || isempty(matrixFieldname)
    matrixFieldname = {'matrix', 'alpha'};
elseif ischar(matrixFieldname)
    matrixFieldname = {matrixFieldname};    
end

for iField = matrixFieldname
    % field name for this round
    thisfield = iField{1};
    
    % continue only when this field name exists
    if ~isfield(stimDir, iField)
        warning('%s is not a fieldname in stimDir.', thisfield);
        continue;
    end
    
    % only resize if this field exists for this stimulus
    isAva = ~cellfun(@isempty, {stimDir.(thisfield)});
    resizeStimMat = cellfun(@(x) imresize(x, scale), {stimDir(isAva).(thisfield)}, 'uni', false);
    [stimDir(isAva).(['resize' thisfield])] = resizeStimMat{:};
    
end

end