function stimDir = im_rgb2gray(stimDir, matrixFn)
% stimDir = im_rgb2gray(stimDir, matrixFn)
%
% Convert the color images to gray-scale.
%
% Inputs:
%    stimDir   <struct> the image dir (generated by im_readdir.m).
%    matrixFn  <cell str> field names of matrices to be converted. Default 
%               is 'matrix'.
%
% Output:
%    stimDir   <struct> the stimulus structure with the gray-scaled matrix.
%
% Created by Haiyang Jin (2021-12-09)
%
% See also:
% im_dir; im_readdir

if ~exist('matrixFn', 'var') || isempty(matrixFn)
    matrixFn = 'matrix';
end

% only convert to gray-scale if the field exists
isAva = ~cellfun(@isempty, {stimDir.(matrixFn)});
updatedStimMat = cellfun(@(x) rgb2gray(x), {stimDir(isAva).(matrixFn)}, 'uni', false);
[stimDir(isAva).(['gray' matrixFn])] = updatedStimMat{:};

end