function fileDir = im_resizevd(fileDir, scale, outPath)
% fileDir = im_resizevd(fileDir, scale, outPath)
%
% Reads, resizes, and saves the videos (*.avi).
%
% Inputs:
%    fileDir        <struct> the image dir (generated by im_dir.m).
%    scale          <num> the scale to be applied to the image. If scale <
%                    1, the output image will be smaller; if scale > 1, the
%                    output image will be larger. E.g., to resize an image
%                    of size A to Size B, the scale should be set as B/A.
%    outPath        <str> where to save the output videos.
%
% Output:
%    fileDir        <struct> with additional information about the resized
%                    video width and height.
%
% Created by Haiyang Jin (2021-12-19)

if ~exist('scale', 'var') || isempty(scale)
    scale = 0.5;
end

if ~exist('outPath', 'var') || isempty(outPath)
    outPath = fullfile(pwd, 'Videos_resized');
end
ptb_mkdir(outPath);

% make subdir if needed
subfolders = unique({fileDir.condition});
subfolders(strcmp(subfolders, 'main')) = [];
cellfun(@ptb_mkdir, fullfile(outPath, subfolders));

nVd = length(fileDir);

% resize for each video separately
for iVd = 1:nVd

    % video reader handles (to be improved)
    vptr = VideoReader(fullfile(fileDir(iVd).folder, fileDir(iVd).name));
    
    % save the videos in subdir if needed
    if ~strcmp(fileDir(iVd).condition, 'main')
        thecond = fileDir(iVd).condition;
    else
        thecond = '';
    end

    % remove the file extension
    [~, fn] = fileparts(fileDir(iVd).name);

    % video writer handler
    writer = VideoWriter(fullfile(outPath, thecond, fn), 'Motion JPEG AVI');

    % resize and save each frame
    open(writer);

    while hasFrame(vptr)
        % read each frame
        thisFrame = readFrame(vptr);
        % resize each frame
        resizeFrame = imresize(thisFrame, scale);
        % save the resized frame in the video
        writeVideo(writer,resizeFrame);
    end

    % save the size of the video/frame
    fileDir(iVd).width = size(resizeFrame, 2);
    fileDir(iVd).height = size(resizeFrame, 1);

    close(writer);
end
end