function im_writedir(stimDir, outputPath, matrixFieldname, imgExt, imgString)
% im_writedir(stimDir, outputPath, matrixFieldname, imgExt, imgString)
%
% This function write image directory into image files with specific image
% file type.
%
% Inputs:
%     stimDir           <structure> stimulus structure [generated by
%                       im_readdir].
%     outputPath        <string> the path to the output folder
%     matrixFieldname   <string> the fieldname to be saved.
%     imgExt            <string> image extensions. if isempty, images will
%                       be saved as their original formats.
%     imgString         <string> extra strings to be added at the end of
%                       the file name.
%
% Output:
%     creat images in the outputPath
%
% Created by Haiyang Jin (20-Feb-2020)


% creat the default output folder
if nargin < 2 || isempty(outputPath)
    outputPath = fullfile(pwd, 'newimages');
end
if ~exist(outputPath, 'dir')
    mkdir(outputPath);
end

if nargin < 3 || isempty(matrixFieldname)
    matrixFieldname = 'matrix';
elseif ~isfield(stimDir, matrixFieldname)
    error('%s is not a valid fieldname in stimDir.', matrixFieldname);
end

% if imgExt is empty, images will be saved in their original formats
if nargin < 4 || isempty(imgExt)
    imgExt = '';
    newExt = false;
else
    newExt = true;
    
    % add point to the extention if necessary
    if ~strcmp(imgExt(1), '.')
        imgExt = ['.' imgExt];
    end
end

if nargin < 5 || isempty(imgString)
    
    switch matrixFieldname
        case 'matrix'
            imgString = '';
        case 'psmatrix'
            imgString = '_ps';
        case 'bsmatrix'
            imgString = '_bs';
    end
    
end

%%
% creat the output folder (and its subfolders)
if isfield(stimDir, 'condition')
    subFolders = unique({stimDir.condition});
    subFolders(strcmp(subFolders, 'main')) = [];
    tempFolders = fullfile(outputPath, subFolders);
    isSub = true;
else
    tempFolders = {outputPath};
    isSub = false;
end

% creat the folder and subfolders
cellfun(@mkdir, tempFolders);

% number of images to be written
nImg = numel(stimDir);

for iImg = 1:nImg
    
    % structure for this image
    thisImg = stimDir(iImg);
    
    % add new extension if needed
    [~, fn, ext] = fileparts(thisImg.fn);
    
    % add the image strings
    theFn = [fn imgString];
    
    % set the image extension
    if newExt
        theExt = imgExt;
    else
        theExt = ext;
    end
    
    % add subfolders to the path
    if isSub && ~strcmp(thisImg.condition, 'main')
        thePath = fullfile(outputPath, thisImg.condition);
    else
        thePath = outputPath;
    end
    
    % write the image
    imwrite(thisImg.(matrixFieldname), fullfile(thePath, [theFn theExt]));
    
end

end